cloud:
  accountId: 0101010101

image:
  tag: 0.0.1
  repository: hachikoapp/timeoff-management-app
  imagePullPolicy: Always

database:
  dbEndpoint: rds_endpoint
  dbName: rds_name
  dbUsername: rds_username
  dbPassword: rds_password
  dbDialect: rds_dialect
